version: '3'

services:

  tasks:
    build:
      context: ./services/task
      dockerfile: Dockerfile
    volumes:
      - './services/task:/usr/src/app'
    ports:
      - 8081:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@tasks-db:5432/tasks
      - DATABASE_TEST_URL=postgres://postgres:postgres@tasks-db:5432/tasks_test
      - SECRET_KEY=PB3aGvTmCkzaLGRAxDc3aMayKTPTDd5usT8gw4pCmKOk5AlJjh12pTrnNgQyOHCH
    depends_on:
      - tasks-db

  tasks-db:
    build:
      context: ./services/task/src/db
      dockerfile: Dockerfile
    container_name: "tasks-db"    
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /fapp/node_modules
      - .:/fapp
    links:
      - tasks
    depends_on:
      - tasks
    
  tests:
    container_name: tests
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /fapp/node_modules
      - .:/fapp
    command: npm run test

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
        - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 8084:8080
    environment:
      - URL=swagger.json
    depends_on:
      - tasks

