"""empty message

Revision ID: 4878503ddb8f
Revises: f22401dd60a3
Create Date: 2020-04-27 15:20:23.766113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4878503ddb8f'
down_revision = 'f22401dd60a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    # ### end Alembic commands ###
