"""empty message

Revision ID: d5bb894c5ae4
Revises: 9c2fa84424df
Create Date: 2020-05-12 08:21:09.145592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5bb894c5ae4'
down_revision = '9c2fa84424df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderlines')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.create_table('orderlines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_price_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discounted_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vat_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orderlines_pkey')
    )
    # ### end Alembic commands ###
